### ISSUE TITLE
Error: Extra margins 

### ISSUE THREAD

**Issue by melissamcewen** [MarceloCelio/TeaCozy#4]
https://github.com/MarceloCelio/TeaCozy/blob/master/resources/css/style.css#L44-L53

(Important) This looks fine unless your screen width is over 1200px. Then it adds a margin as shown in the picture here. 
![margin-issue](https://user-images.githubusercontent.com/1251094/34704596-d73ca7ce-f4bf-11e7-8334-7cb07f37182c.jpg)

I recommend removing the width from the body
https://github.com/MarceloCelio/TeaCozy/blob/master/resources/css/style.css#L9 

and to center .mission use margin 0 auto
```
.mission {
display: flex;
padding-top: 70px;
background-image: url("../images/img-mission-background.jpg");
background-size: cover;
height: 700px;
width: 1200px;
align-items: center;
margin: 0 auto;
}
```

Also you'll want to make these changes to the other elements laid out that way (.locations, .footer). 

another great option is wrap all these elements (.mission, .locations, .footer) in a new div called .main. This is so you don't need to set the width for all these since it's all the same for all three.

```css
/* Main Section */

.main {
  padding-top: 69px; /* To offset fixed header */
  opacity: 0.9;
  width: 1200px;
  margin: auto;
}

```
